### ISSUE TITLE
pic16f877a is not recognized

### ISSUE THREAD

**Issue by hernandik** [makerprojects/ProgramPic#2]
I'm trying to program a pic 16f877a.
I inserted the folow configs: 
{s_pic16f877a, 0x0E28, 8192, 0x2000, 0x2100, 8, 256, 0, 0, FLASH4, EEPROM },
I installed the arduino code and run the host program. But I only receive the message:
"Unsupported device in programmer, ID = 0E28"
I try to show all variables, but only receive this fields in serial communication. Seens like a Arduino bug reading the DeviceId.

Initializing programmer ...
Device name: ConfigWord = 3FFF
Device name: DeviceID = 0E28
COM7

I also try one pic 12f675 and it worked perfectly. I am sure that my 16f877a are working, as I tested several pieces that I have in my bin and all then had this same issue.

Could you please help-me debuging this issue?

**Comment by makerprojects** [comment]
Did you also add the ‘MCLR_first’ at the end (see below)?

 

{s_pic16f887, 0x2080, 8192, 0x2000, 0x2100, 9, 256, 0, 0, FLASH4, EEPROM, MCLR_first}

 

 

Von: Hernandi F. Krammes F. [mailto:notifications@github.com] 
Gesendet: Montag, 15. Januar 2018 01:23
An: makerprojects/ProgramPic
Cc: Subscribed
Betreff: [makerprojects/ProgramPic] pic16f877a is not recognized (#2)

 

I'm trying to program a pic 16f877a.
I inserted the folow configs:
{s_pic16f877a, 0x0E28, 8192, 0x2000, 0x2100, 8, 256, 0, 0, FLASH4, EEPROM },
I installed the arduino code and run the host program. But I only receive the message:
"Unsupported device in programmer, ID = 0E28"
I try to show all variables, but only receive this fields in serial communication. Seens like a Arduino bug reading the DeviceId.

Initializing programmer ...
Device name: ConfigWord = 3FFF
Device name: DeviceID = 0E28
COM7

I also try one pic 12f675 and it worked perfectly. I am sure that my 16f877a are working, as I tested several pieces that I have in my bin.

Could you please help-me debuging this issue?

**Comment by hernandik** [comment]
I found the problem source.
{s_pic16f877a, 0x0E28, 8192, 0x2000, 0x2100, 8, 256, 0, 0, FLASH4, EEPROM,MCLR_first },
should be:
{s_pic16f877a, 0x0E2**0**, 8192, 0x2000, 0x2100, 8, 256, 0, 0, FLASH4, EEPROM,MCLR_first },

We could put a comment in the code to help us in the future, that the last 4 or 5 bits (877 is 5, 877a is 4 bits) represents the revision. Or we could change the code to ignore the last bits of the internal table.

**Comment by makerprojects** [comment]
Thank you very much for improving the program. I will merge the changes into the master branch.
